
image: atlassian/default-image:2

clone: # help to clone our source here
  depth: full
pipelines: # We set up all the pipeline or actions beneath
  default: # here most always trigger before any other pipeline
  - step:
      script:
        - npm install
        - npm run start
        - cd ./dist
        - git init
        - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master