
image: atlassian/default-image:2

clone:
  depth: full
pipelines:
  default:
  - step:
      services:
      - docker
      caches:
        - node
      script:
        - npm install
        - npm install -g @angular/cli
        - ng build
        - ls -ltr
        - pwd
        - git status
        - git cd ./dist
        - git push git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master